INSERT INTO WORDS VALUES(1, 'ACTION');
INSERT INTO WORDS VALUES(2, 'ADD');
INSERT INTO WORDS VALUES(3, 'ALL');
INSERT INTO WORDS VALUES(4, 'ALLOCATE');
INSERT INTO WORDS VALUES(5, 'ALTER');
INSERT INTO WORDS VALUES(6, 'ANY');
